version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - remote_cache:
        key:composer-v1-{{checksum "composer.lock"}} ##保存されたキャッシュの復元
      - run: php -r "copy('https://raw.githubusercontent.com/composer/getcomposer.org/master/web/installer', 'composer-setup.php');" &&     php composer-setup.php &&     php -r "unlink('composer-setup.php');" &&     mv composer.phar /usr/local/bin/composer
      - run: composer install
      - save_cache:
        key:composer-v1-{{checksum "composer.lock"}}
        paths:
          - vendor
      - run: npm ci
      - run: npm run dev
      - run:
          name: php test
          command: vendor/bin/phpunit